[package]
name = "json-resume"
version = "0.1.0"
edition = "2021"

[features]
validate = ["serde_valid"]

[dependencies]
regex = "1.7.1"
serde = { version = "1.0.156", features = ["derive"] }
serde_valid = { version = "0.13.0", optional = true }

[dev-dependencies]
serde_json = "1.0.94"
