on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: "The git tag to publish"
        required: true
        type: string

name: Publish library

jobs:
  publish-cratesio:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment: "publish-crates.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag-name }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Upload library to crates.io
        uses: actions-rs/cargo@v1
        # The lib crate might fail, when no changes to it where made
        # This `if` makes sure the publishing continues
        continue-on-error: true
        with:
          command: publish
          args: -p json-resume
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
