on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: "The git tag to publish"
        required: true
        type: string

name: Publish

jobs:
  publish-cratesio:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment: "publish-crates.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag-name }}

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Upload library to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p json-resume
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
