name: Reviewdog

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  typos:
    name: runner / typos
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run typos with reviewdog
        uses: Shemnei/reviewdog-action-typos@v0
        with:
          reporter: github-check
          level: error
          fail_on_error: true

  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run languagetool with reviewdog
        uses: reviewdog/action-languagetool@v1
        with:
          reporter: github-check
          level: info
          patterns: |
            !guide/ci/dictionary.txt

  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint with reviewdog
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          level: error
          fail_on_error: true
